### ISSUE TITLE
test suite failure on ubuntu with xclip

### ISSUE THREAD

**Issue by DanBurton** [jetho/Hclip#3]
When I ran the test suite on my mac (with pbcopy/pbpaste), it worked correctly and the test suite passed.
However, when it ran on the stackage build server, and when I run it on the `snoyberg/stackage:nightly` docker image (using xclip version 0.12), it fails.

How to reproduce:

```
docker run -it snoyberg/stackage:nightly
stack unpack Hclip-3.0.0.3
cd Hclip-3.0.0.3
stack init --resolver nightly-2016-06-08
stack test
```

Results:

```
Tests
  Unit tests
    Clear Clipboard:                          OK (0.03s)
    Set Clipboard:                            FAIL (0.02s)
      expected: "Haskell"
       but got: ""
    Get Clipboard:                            FAIL (0.01s)
      expected: "Haskell"
       but got: ""
    Modify Clipboard:                         FAIL (0.03s)
      expected: "lleksaH"
       but got: ""
    Modify Clipboard and return new contents: FAIL (0.02s)
      expected: "lleksaH"
       but got: ""

4 out of 5 tests failed (0.12s)
```

**Comment by jetho** [comment]
Thanks for your report!
I think this is because of the way X selections and tools like xclip and xsel work.
They work by forking and destroying processes and I'm suspecting that running these tools many times in a short time span (for example in the test suite) creates some kind of race condition.
For now, I disabled the test suite and I'll upload a new release (3.0.0.4) to hackage.
